server:
  servlet:
    encoding:
      force: 'true'
      enabled: 'true'
      charset: UTF-8
    context-path: /
  port: '8080'
  ssl:
    enabled: 'false'
spring:
  redis:
    lettuce:
      pool:
        max-active: '10'
        max-idle: '10'
        min-idle: '2'
    host: 127.0.0.1
    port: '6379'
  servlet:
    multipart:
      max-file-size: 1MB
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: 'true'
  datasource:
    password: '1234'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: c202
    url: jdbc:mysql://localhost:3306/trisy?serverTimezone=Asia/Seoul
  profiles:
    include: oauth
jwt:
  secret: asdfa1!r1rf#6zcwmo&1072%4r624rfja;awef24rq][.vrkafr!*ja$2j#via;erfmcqjedzdfq$
