server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  ssl:
    enabled: false

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S08P22C202
    username: S08P22C202@stg-yswa-kr-practice-db-master
    password: GfNj2advQi

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    port: 6379
    host: j8c202.p.ssafy.io
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
  servlet:
    multipart:
      max-file-size: 1MB
  profiles:
    include: oauth
jwt:
  secret: asdfa1!r1rf#6zcwmo&1072%4r624rfja;awef24rq][.vrkafr!*ja$2j#via;erfmcqjedzdfq$
