server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  ssl:
    enabled: false

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j8c202.p.ssafy.io:3306/s08p22c202
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    port: 6379
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
  servlet:
    multipart:
      max-file-size: 1MB
  profiles:
    include: oauth
jwt:
  secret: asdfa1!r1rf#6zcwmo&1072%4r624rfja;awef24rq][.vrkafr!*ja$2j#via;erfmcqjedzdfq$

cloud:
  aws:
    credentials:
      accessKey : AKIA5TYLFPVAN2E7ZAGC
      secretKey : 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
    s3:
      bucket: trisy
    region:
      static: ap-northeast-2
    stack:
      auto: false
